apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-webserver
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-webserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-webserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-webserver
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
